// <auto-generated />
using System;
using EFCoreMigrationNet7SqlLite.DbContexts;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace EFCoreMigrationNet7SqlLite.Migrations
{
    [DbContext(typeof(BooksContext))]
    [Migration("20230211041255_InitialMigration")]
    partial class InitialMigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "7.0.2");

            modelBuilder.Entity("EFCoreMigrationNet7SqlLite.Entities.Author", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            Id = new Guid("e97cd87c-d2f9-4664-aa38-632fad458171"),
                            FirstName = "George",
                            LastName = "RR Martin"
                        },
                        new
                        {
                            Id = new Guid("24bda992-eecc-4d01-adcb-0785283ac830"),
                            FirstName = "Stephen",
                            LastName = "Fry"
                        },
                        new
                        {
                            Id = new Guid("29d414cc-73a7-415d-aa47-d881d50eef7d"),
                            FirstName = "James",
                            LastName = "Elroy"
                        },
                        new
                        {
                            Id = new Guid("04b0fee0-1720-454f-b4cd-a60491df7e15"),
                            FirstName = "Douglas",
                            LastName = "Adams"
                        });
                });

            modelBuilder.Entity("EFCoreMigrationNet7SqlLite.Entities.Book", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AuthorId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasMaxLength(2500)
                        .HasColumnType("TEXT");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AuthorId");

                    b.ToTable("Books");

                    b.HasData(
                        new
                        {
                            Id = new Guid("978567bf-0099-4b83-bf93-bafc6cb4222f"),
                            AuthorId = new Guid("e97cd87c-d2f9-4664-aa38-632fad458171"),
                            Description = "The book that seems impossible to write",
                            Title = "The Winds of Winter"
                        },
                        new
                        {
                            Id = new Guid("88116d67-167c-4271-893e-fcf3589a3db2"),
                            AuthorId = new Guid("e97cd87c-d2f9-4664-aa38-632fad458171"),
                            Description = "The Greek myths are amongst the best stories ever told",
                            Title = "Mythos"
                        },
                        new
                        {
                            Id = new Guid("9ca0a641-b6eb-43ea-95c3-b12e6a339483"),
                            AuthorId = new Guid("24bda992-eecc-4d01-adcb-0785283ac830"),
                            Description = "A Game of Thrones is the first novel in A Song of Ice and Fire",
                            Title = "A Game of Thrones"
                        },
                        new
                        {
                            Id = new Guid("7e54e12f-1834-49a4-b4d6-05d62c397732"),
                            AuthorId = new Guid("29d414cc-73a7-415d-aa47-d881d50eef7d"),
                            Description = "a 1995 novel by James Ellroy",
                            Title = "American Tabloid"
                        },
                        new
                        {
                            Id = new Guid("d0d4b0a1-9fd9-47d9-9eac-4903ed444889"),
                            AuthorId = new Guid("04b0fee0-1720-454f-b4cd-a60491df7e15"),
                            Description = "The Hitchicker's Guide to the Galaxy",
                            Title = "The Hitchhiker's Guide to the Galaxy"
                        });
                });

            modelBuilder.Entity("EFCoreMigrationNet7SqlLite.Entities.Book", b =>
                {
                    b.HasOne("EFCoreMigrationNet7SqlLite.Entities.Author", "Author")
                        .WithMany()
                        .HasForeignKey("AuthorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");
                });
#pragma warning restore 612, 618
        }
    }
}
